### PR TITLE
Rewrite security consideration and update reference with published RFC

### PR DESCRIPTION
**Pull request by billwuqin**
Rewrite security section based on Security YANG template.
Add security consideration to the groupings of the module defined this draft.
Add security consideration to system capability extension.

### CODE REVIEW

**Review by kwatsen — CHANGES_REQUESTED** [review]
Please add this line to the top of the `Regarding the "ietf-list-pagination" YANG Module` section:
```
<t>This section follows the template defined in <xref section="3.7.1" target="RFC8407"/>.</t>
```

Also, please rename the `Regarding the "ietf-list-pagination" YANG Module` section:

    NEW: `Considerations for the "ietf-list-pagination" YANG Module`

**Comment by billwuqin** [comment]
I have incorporated Kent's proposed change, thanks Kent.

**Review by kwatsen — APPROVED** [review]
LGTM

**Comment by kwatsen** [comment]
This PR is just for the LP-draft.  
My two updates apply also to the LP-nc and LP-rc drafts as well.
Are PRs open for these other two drafts too?

**Pull request closed without merging**
